common:
  notification:
    exception:
      color: "#36a64f"
      webhook-url: "https://hooks.slack.com/services/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"
      channel-name: "error"

spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://220.230.125.26:3306/clean_web_culture
    username: crw
    password: crw
    hikari:
      max-lifetime: 300000
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: live
  datasource:
    url: jdbc:mariadb://220.230.125.26:3306/clean_web_culture
    username: crw
    password: crw
    hikari:
      max-lifetime: 300000
  jpa:
    hibernate:
      ddl-auto: update